import Link from "next/link";
import { Activity, AlertTriangle, ArrowRight, CheckCircle2, FileCheck2, FileSearch, LockKeyhole, Route, ShieldCheck, Sparkles, Tags, Waypoints } from "lucide-react";

export default function Home() {
  return <main className="landing-page">
    <nav className="landing-nav">
      <Link href="/" className="landing-brand"><span className="landing-mark">+</span><span><strong>SETUX<span>AI</span></strong><small>GOVERNMENT SERVICES</small></span></Link>
      <div className="landing-nav-links"><a href="#how-it-works">How it works</a><a href="#solution">Our solution</a><a href="#for-officers">For officers</a><a href="#security">Security</a></div>
      <div className="landing-actions"><Link href="/auth" className="landing-signin">Sign in</Link><Link href="/auth" className="landing-cta">Create account <ArrowRight size={15} /></Link></div>
    </nav>
    <section className="landing-hero">
      <div className="hero-copy"><p className="landing-kicker"><span /> INTELLIGENT WORKFLOW AUTOMATION</p><h1>From application<br /><em>to action.</em></h1><p className="hero-description">SetuX helps citizens submit better applications and helps government teams prepare, route, and track every case with clarity.</p><div className="hero-actions"><Link href="/auth" className="landing-cta hero-button">Get started <ArrowRight size={16} /></Link><a href="#how-it-works" className="hero-secondary">See how it works <span>↓</span></a></div><div className="hero-trust"><ShieldCheck size={16} /><span>Secure by design</span><i /><CheckCircle2 size={16} /><span>Human decisions stay human</span></div></div>
      <div className="hero-visual"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="hero-case-card"><div className="case-card-top"><span className="mini-brand"><Sparkles size={14} /> SETUX AI</span><span className="case-live"><i /> LIVE CASE</span></div><p className="case-label">AI CASE PREPARATION</p><h2>Income Certificate</h2><p className="case-ref">SETUX-2026-000184</p><div className="case-progress"><div><span>Application readiness</span><strong>94%</strong></div><div className="progress-track"><span /></div></div><div className="case-checks"><div><CheckCircle2 size={16} /><span>Information extracted</span><b>Ready</b></div><div><CheckCircle2 size={16} /><span>Documents validated</span><b>3 / 3</b></div><div><Route size={16} /><span>Routed to Revenue</span><b>Assigned</b></div></div><div className="case-footer"><div className="hero-avatar">AM</div><span>Ananya Mehta<br /><small>Assigned officer</small></span><ArrowRight size={16} /></div></div><div className="floating-insight"><Sparkles size={15} /><span><strong>Case prepared</strong><small>Ready for human review</small></span></div></div>
    </section>
    <section className="landing-strip"><div><strong>One clear workflow.</strong><span>Less manual work for teams. More visibility for citizens.</span></div><div className="strip-stat"><strong>3×</strong><span>faster case preparation</span></div><div className="strip-stat"><strong>100%</strong><span>human-led decisions</span></div><div className="strip-stat"><strong>24/7</strong><span>application visibility</span></div></section>
    <section className="landing-section" id="how-it-works"><div className="landing-section-heading"><p className="landing-kicker">THE SETUX WORKFLOW</p><h2>Good applications move<br /><em>with confidence.</em></h2><p>Every submission becomes a structured, validated, and traceable case before it reaches an officer.</p></div><div className="workflow-grid"><WorkflowStep number="01" icon={FileCheck2} title="Submit once" text="Citizens upload an application and the documents that support it." /><WorkflowStep number="02" icon={Sparkles} title="SetuX prepares" text="Information is extracted, checked, classified, and routed explainably." /><WorkflowStep number="03" icon={ShieldCheck} title="Officers decide" text="Authorized officers review the prepared case and keep the final say." /></div></section>
    <section className="solution-section" id="solution"><div className="landing-section-heading"><p className="landing-kicker">THE SOLUTION</p><h2>Every manual bottleneck,<br /><em>made visible and actionable.</em></h2><p>SetuX turns a raw citizen submission into a structured case, while keeping government officers in control.</p></div><div className="solution-grid"><SolutionCard icon={FileSearch} number="01" title="OCR & extraction" text="Read uploaded forms and documents, then turn unstructured text into useful fields like name, address, income, and date of birth." /><SolutionCard icon={Tags} number="02" title="Smart classification" text="Identify the service and department automatically, with confidence shown clearly for human review." /><SolutionCard icon={FileCheck2} number="03" title="Validation checks" text="Compare required fields and documents against service rules, then highlight missing or incomplete items." /><SolutionCard icon={Waypoints} number="04" title="Explainable routing" text="Send each case to the right department and officer using workload, availability, and a visible reason." /><SolutionCard icon={AlertTriangle} number="05" title="Priority & escalation" text="Surface urgent cases, monitor ageing work, and flag delayed applications before they become bottlenecks." /><SolutionCard icon={Activity} number="06" title="Live operations view" text="Give citizens status visibility and administrators a live view of processing time, backlog, and officer performance." /></div></section>
    <section className="landing-section officer-section" id="for-officers"><div className="officer-copy"><p className="landing-kicker">BUILT FOR PUBLIC SERVICE TEAMS</p><h2>A calmer desk.<br /><em>A clearer queue.</em></h2><p>Know what needs attention, what is complete, and where work is waiting. SetuX gives officers a focused case view instead of another pile of paperwork.</p><Link href="/auth" className="landing-text-link">Explore the workspace <ArrowRight size={15} /></Link></div><div className="queue-preview"><div className="queue-header"><div><span>OFFICER WORKSPACE</span><strong>My case queue</strong></div><span className="queue-pill"><i /> 06 active cases</span></div><div className="queue-row selected"><div className="queue-file"><FileCheck2 size={17} /></div><div><strong>SETUX-2026-000184</strong><span>Income Certificate · Revenue</span></div><span className="queue-status">Under review</span></div><div className="queue-row"><div className="queue-file mint"><FileCheck2 size={17} /></div><div><strong>SETUX-2026-000143</strong><span>Scholarship · Education</span></div><span className="queue-status done">Completed</span></div><div className="queue-row"><div className="queue-file amber"><FileCheck2 size={17} /></div><div><strong>SETUX-2026-000091</strong><span>Pension · Social Welfare</span></div><span className="queue-status attention">Needs attention</span></div></div></section>
    <section className="security-section" id="security"><div><LockKeyhole size={20} /><p className="landing-kicker">TRUST IS PART OF THE PRODUCT</p><h2>Private documents.<br />Transparent decisions.</h2></div><p>Role-based access, private storage, database security policies, and an audit trail keep sensitive government workflows accountable from submission to completion.</p><Link href="/auth" className="landing-cta">Enter SetuX <ArrowRight size={15} /></Link></section>
    <footer className="landing-footer"><Link href="/" className="landing-brand"><span className="landing-mark">+</span><span><strong>SETUX<span>AI</span></strong><small>GOVERNMENT SERVICES</small></span></Link><span>Intelligent Workflow Automation for Government Services</span><span>© 2026 SetuX AI</span></footer>
  </main>;
}

function WorkflowStep({ number, icon: Icon, title, text }: { number: string; icon: typeof FileCheck2; title: string; text: string }) {
  return <article className="workflow-step"><span className="workflow-number">{number}</span><div className="workflow-icon"><Icon size={21} /></div><h3>{title}</h3><p>{text}</p></article>;
}

function SolutionCard({ number, icon: Icon, title, text }: { number: string; icon: typeof FileSearch; title: string; text: string }) {
  return <article className="solution-card"><div className="solution-card-top"><div className="solution-icon"><Icon size={19} /></div><span>{number}</span></div><h3>{title}</h3><p>{text}</p></article>;
}