"use client";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Check, CheckCircle2, Clock3, FileCheck2, FolderKanban, RefreshCw, ShieldCheck, UserPlus, Users } from "lucide-react";
import { supabase } from "../lib/supabase";
type App = { id:string; application_number:string; status:string; department_id:string|null; department:string; service:string; citizen:string; officer_id:string|null; officer:string; due_at:string|null; review:string|null };
type Officer = { id:string; full_name:string; email:string; department_id:string|null; department:string; is_available:boolean; max_active_cases:number };
type Department = { id:string; name:string; sla_hours:number };
const closed=["COMPLETED","REJECTED"]; const label=(v:string)=>v.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()); const fmt=(v:string|null)=>v?new Date(v).toLocaleString("en-GB",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}):"Not set";
export function AdminControlPanel(){
 const [apps,setApps]=useState<App[]>([]); const [officers,setOfficers]=useState<Officer[]>([]); const [departments,setDepartments]=useState<Department[]>([]); const [selected,setSelected]=useState<App|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [staff,setStaff]=useState({name:"",email:"",department:""});
 const load=async()=>{if(!supabase)return;setBusy(true);const [a,o,d,r]=await Promise.all([supabase.from("applications").select("id,application_number,status,department_id,assigned_officer_id,due_at,services(name),departments(name),profiles!applications_user_id_fkey(full_name),officer:profiles!applications_assigned_officer_id_fkey(full_name)").order("updated_at",{ascending:false}),supabase.from("profiles").select("id,full_name,email,department_id,is_available,max_active_cases,departments(name)").eq("role","OFFICER").order("full_name"),supabase.from("departments").select("id,name,sla_hours").order("name"),supabase.from("application_reviews").select("application_id,review_status,created_at").order("created_at",{ascending:false})]);const fallbackApps=a.error?(await supabase.from("applications").select("id,application_number,status,department_id,assigned_officer_id,services(name),departments(name),profiles!applications_user_id_fkey(full_name),officer:profiles!applications_assigned_officer_id_fkey(full_name)").order("updated_at",{ascending:false})).data:a.data;const fallbackDepartments=d.error?(await supabase.from("departments").select("id,name").order("name")).data:d.data;const reviews=new Map<string,string>();(r.data||[]).forEach((x:any)=>{if(!reviews.has(x.application_id))reviews.set(x.application_id,x.review_status)});setApps((fallbackApps||[]).map((x:any)=>({id:x.id,application_number:x.application_number,status:x.status,department_id:x.department_id,department:x.departments?.name||"Unassigned",service:x.services?.name||"Government service",citizen:x.profiles?.full_name||"Citizen",officer_id:x.assigned_officer_id,officer:x.officer?.full_name||"Not assigned",due_at:x.due_at||null,review:reviews.get(x.id)||null})));setOfficers((o.data||[]).map((x:any)=>({...x,department:x.departments?.name||"No department",is_available:x.is_available!==false,max_active_cases:x.max_active_cases||10})));setDepartments((fallbackDepartments||[]).map((x:any)=>({...x,sla_hours:x.sla_hours||72})));setBusy(false)};
 useEffect(()=>{void load()},[]); const active=(id:string)=>apps.filter(a=>a.officer_id===id&&!closed.includes(a.status)).length; const late=(a:App)=>!closed.includes(a.status)&&!!a.due_at&&new Date(a.due_at)<new Date(); const eligible=useMemo(()=>officers.filter(o=>o.department_id===selected?.department_id&&o.is_available&&active(o.id)<o.max_active_cases).sort((a,b)=>active(a.id)-active(b.id)),[officers,selected,apps]);
 const rpc=async(name:string,args:any,ok:string)=>{if(!supabase)return;setBusy(true);const {error,data}=await supabase.rpc(name,args);setMessage(error?error.message:ok.replace("{count}",String(data??"")));if(!error){setSelected(null);await load()}setBusy(false)};
 const addOfficer=async(e:React.FormEvent)=>{e.preventDefault();await rpc("add_registered_officer",{p_email:staff.email,p_department_id:staff.department,p_full_name:staff.name||null},"Officer added.");setStaff({name:"",email:"",department:""})};
 const unassigned=apps.filter(a=>!a.officer_id&&!closed.includes(a.status)); const delayed=apps.filter(late);
 return <div className="page-wrap"><div className="page-heading"><div><p className="eyebrow">ADMINISTRATION / OPERATIONS</p><h1>Department operations control</h1><p className="subheading">New cases are automatically balanced across available officers; admin monitors exceptions and final approval.</p></div><button className="quiet-btn" disabled={busy} onClick={()=>void load()}><RefreshCw size={15} className={busy?"spin":""}/> Refresh</button></div><div className="stat-grid"><Stat icon={FolderKanban} tone="peach" label="All applications" value={apps.length} note="Every department"/><Stat icon={Users} tone="amber" label="Unassigned" value={unassigned.length} note="No officer capacity"/><Stat icon={AlertTriangle} tone="amber" label="Delayed" value={delayed.length} note="Past SLA deadline"/><Stat icon={CheckCircle2} tone="green" label="Completed" value={apps.filter(a=>a.status==="COMPLETED").length} note="Admin final approvals"/></div>{message&&<p className="action-message admin-message">{message}</p>}
 <section className="department-command"><div className="section-title"><div><h2>Department workload & deadlines</h2><p>Auto divide uses the least-loaded officer with free capacity.</p></div></div><div className="department-command-grid">{departments.map(d=>{const dc=apps.filter(a=>a.department_id===d.id), os=officers.filter(o=>o.department_id===d.id), available=os.filter(o=>o.is_available), wait=dc.filter(a=>!a.officer_id&&!closed.includes(a.status)), overdue=dc.filter(late);return <article className={`department-command-card ${available.length?"":"attention"}`} key={d.id}><div className="department-command-head"><div><strong>{d.name}</strong><small>{dc.filter(a=>a.status==="COMPLETED").length} completed · {dc.filter(a=>!closed.includes(a.status)).length} remaining</small></div>{!available.length&&<span className="no-officer"><AlertTriangle size={12}/> No officer available</span>}</div><div className="department-metrics"><span><b>{available.length}</b> available</span><span><b>{wait.length}</b> unassigned</span><span className={overdue.length?"late":""}><b>{overdue.length}</b> delayed</span></div><div className="department-sla"><label>SLA hours<input type="number" min="1" defaultValue={d.sla_hours} onBlur={e=>Number(e.target.value)!==d.sla_hours&&void rpc("set_department_sla",{p_department_id:d.id,p_sla_hours:Number(e.target.value)},"SLA updated.")}/></label><button className="quiet-btn" disabled={busy||!available.length||!wait.length} onClick={()=>void rpc("auto_assign_department_backlog",{p_department_id:d.id},"{count} cases distributed.")}>Auto divide ({wait.length})</button></div></article>})}</div></section>
 <div className="admin-workspace"><section className="admin-case-panel"><div className="section-title"><div><h2>All applications</h2><p>Open a case to choose an officer or make a final decision.</p></div><span className="role-pill admin"><ShieldCheck size={14}/> Admin only</span></div><div className="admin-case-list">{apps.map(a=><button key={a.id} className={`admin-case-row ${selected?.id===a.id?"selected":""}`} onClick={()=>setSelected(a)}><div><strong>{a.application_number}</strong><span>{a.citizen} · {a.service}</span><small>{a.department} · Due {fmt(a.due_at)}</small></div><div className="admin-case-meta"><span className={`status ${late(a)?"amber":a.status==="COMPLETED"?"green":"blue"}`}>{late(a)?"Delayed":a.review==="VERIFIED"?"Verified":label(a.status)}</span><small>{a.officer}</small></div></button>)}</div></section><aside className="assignment-card">{selected?<><p className="eyebrow">CASE CONTROL</p><h2>{selected.application_number}</h2><p className="assignment-service">{selected.service} · {selected.department}</p><div className="detail-list"><div><span>Due by</span><strong className={late(selected)?"late-text":""}>{fmt(selected.due_at)}</strong></div><div><span>Verifier</span><strong>{selected.officer}</strong></div><div><span>Review</span><strong>{selected.review?label(selected.review):"Awaiting officer"}</strong></div></div><div className="assignment-section"><strong><FileCheck2 size={15}/> Assign verifier</strong><p>Sorted by lowest active workload.</p>{eligible.length?<div className="officer-picker">{eligible.map(o=><button key={o.id} onClick={()=>void rpc("assign_application_to_officer",{p_application_id:selected.id,p_officer_id:o.id,p_reason:"Admin workload distribution"},`Assigned to ${o.full_name}.`)}><span>{o.full_name.split(" ").map(x=>x[0]).join("")}</span><div><b>{o.full_name}</b><small>{active(o.id)} / {o.max_active_cases} active</small></div></button>)}</div>:<p className="empty-copy">No available officer with capacity. Add staff below.</p>}</div>{selected.review==="VERIFIED"&&<div className="final-decision"><strong><ShieldCheck size={15}/> Final admin decision</strong><div><button className="reject-btn" onClick={()=>void rpc("admin_decide_application",{p_application_id:selected.id,p_decision:"REJECTED",p_note:"Final rejection by admin"},"Application rejected.")}>Reject</button><button className="primary-btn" onClick={()=>void rpc("admin_decide_application",{p_application_id:selected.id,p_decision:"COMPLETED",p_note:"Final approval by admin"},"Application approved.")}><Check size={15}/> Approve</button></div></div>}</>:<div className="empty-state"><FileCheck2 size={22}/><strong>Select an application</strong><span>Assign it or review final verification.</span></div>}</aside></div>
 <section className="officer-onboarding"><div><p className="eyebrow">STAFF MANAGEMENT</p><h2>Add a registered officer</h2><p>The person must already have a SetuX account; this adds it to the chosen department.</p></div><form onSubmit={addOfficer}><input placeholder="Officer name" value={staff.name} onChange={e=>setStaff({...staff,name:e.target.value})}/><input type="email" required placeholder="Registered email" value={staff.email} onChange={e=>setStaff({...staff,email:e.target.value})}/><select required value={staff.department} onChange={e=>setStaff({...staff,department:e.target.value})}><option value="">Select department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><button className="primary-btn" disabled={busy}><UserPlus size={15}/> Add officer</button></form></section></div>
}
function Stat({icon:Icon,tone,label,value,note}:any){return <div className="stat-card"><div className="stat-top"><span>{label}</span><div className={`stat-icon ${tone}`}><Icon size={17}/></div></div><strong>{value}</strong><small>{note}</small></div>}
